services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./migrations:/migrations:z
      - ./migrations/run-migrations.sh:/docker-entrypoint-initdb.d/run-migrations.sh:z
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
