---

is_debug: true
logs: Text
listen:
  bind_ip: 0.0.0.0
  port: 8080
  write_timeout: 15
  read_timeout: 15
database:
  db_host: localhost
  db_port: 5432
  username: postgres
  password: 1234
  db_name: postgres
  ssl_mode: disable
cache:
  redis_host: localhost
  redis_port: 6379
  redis_db: 0
kafka:
  brokers: "localhost:9092"